name: Deploy Github Pages
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: 'pages'
      cancel-in-progress: true

    env:
      PAGES_BASE_URL: vue-grade-helper
      PR_PATH: preview/${{github.event.number}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (Prod)
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Build (Preview)
        if: github.ref != 'refs/heads/main'
        run: npm run build -- --base=${{ env.PAGES_BASE_URL }}/${{ env.PR_PATH }}

      - name: Copy Index to 404
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy (Prod)
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy (Preview)
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref != 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ env.PR_PATH }}

      - name: Comment Preview URL
        uses: hasura/comment-progress@v2.3.0
        if: github.ref != 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: Preview Deployed https://${{ env.GITHUB_REPOSITORY_OWNER }}.github.io/${{ env.PAGES_BASE_URL }}/${{ env.PR_PATH }}