name: Deploy Github Pages
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: 'pages'
      cancel-in-progress: true

    env:
      PAGES_BASE_URL: vue-grade-helper
      PR_PATH: preview/${{github.event.number}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (Prod)
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Copy Index to 404
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy (Prod)
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
